server:
    port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
            ddl-auto: update
    database-platform:   org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mint
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver